# Copy this file to run_cellpose_per_z_config_local.toml and edit local values.

# Set the path to your cellpose model.
model_path = 'example/path/your_model'

# Set the path to your chunked stacks
stack_dir = 'example/path/your_path'

# Choose a flow threshold. The default is 0.4. Increasing flow_threshold makes Cellpose more lenient,
# This can lead to the detection of more cells, especially in crowded or complex images, but may also
# result in less accurate or ill-shaped masks.
flow_threshold = 0.4

# Set normalize to True or False. Should normally be True.
normalize = true

# Choose whether to use GPU. Set False if running on CPU only.
use_gpu = true
