# Copy this file to split_annotated_stacks_config_local.toml and edit local values.

image_path = 'example/path/your_path'
omit_first_and_last = true

subject_id_index = 1
chunk_info_num_parts = 3

mip_first_start_index = 4
mip_first_end_index = 5
mip_last_start_index = 8
mip_last_end_index = 9

section_start_index = 5
section_end_index = 10
