# Copy this file to run_cellpose_per_image_config_local.toml and edit local values.

# Set the path to your cellpose model.
model_path = 'example/path/your_model'

# Set the path to the input image(s). Can be a single tif file or a folder with tif images.
input_path = 'example/path/your_path'

# Set the path where you want the output to be stored.
out_path = 'example/path/your_out_path'

# Choose a flow threshold. The default is 0.4. Increasing flow_threshold makes Cellpose more lenient,
# This can lead to the detection of more cells, especially in crowded or complex images, but may also
# result in less accurate or ill-shaped masks.
flow_threshold = 0.4

# Set normalize to True or False. Should normally be True.
normalize = true

# Choose whether to use GPU. Set False if running on CPU only.
use_gpu = true
