# Copy this file to run_cellpose_per_chunk_config_local.toml and edit local values.

model_path = "example/path/your_model"
chunk_dir = "example/path/your_chunked_image_path"
out_path = "example/path/your_output_path"

reconstruct = false
orig_image_path = ""

flow_threshold = 0.6
normalize = true
use_gpu = true
