# Copy this file to train_model_config_local.toml and edit local values.

# Define directories using pathlib
train_dir = 'example/path/your_train_directory'
test_dir = 'example/path/your_test_directory'

# Specify number of epochs - how many times the model gets to see the training data.
# Recommended setting from cellpose is 100, but longer times may improve performance
n_epochs = 100

# Specify weight decay
weight_decay = 0.1

# Specify learning rate - essentially how quickly the model learns
# Recommended setting from cellpose is 1e-5.
# A lower learning rate may allow you to train for longer without overfitting
learning_rate = 1e-5

# Specify normalization behavior. Should generally be set to True.
normalize = true

# Choose whether to use GPU. Set False if running on CPU only.
use_gpu = true

# Give a descriptor for your model, typically a name for the signal
model_name = 'my_model_name'

# Set a minimum number of masks that must be present in the chunks for them to be used
# Default is 5, but if you have very sparse stains you might want to set this lower or even to 0
min_train_masks = 5
